"""station_request admin repository.

The Admin UI is the only writer for `status` transitions
(pending → approved / rejected / pending).  Approve creates a fresh
station row whose UUID is generated by the DB; the wire identifier
(``station_name``) is the contract between the gateway and the sender.
"""

from __future__ import annotations

from typing import Any, Literal

import asyncpg


_VALID_TAB = ("pending", "approved", "rejected", "all")


class StationRequestAdminRepository:
    def __init__(self, pool: asyncpg.Pool) -> None:
        self._pool = pool

    async def list_by_status(
        self, status: Literal["pending", "approved", "rejected", "all"] = "pending"
    ) -> list[dict[str, Any]]:
        if status not in _VALID_TAB:
            raise ValueError(f"invalid status filter: {status}")
        if status == "all":
            rows = await self._pool.fetch(
                """
                SELECT station_name, first_seen, last_seen, attempts, status, notes
                  FROM station_request
              ORDER BY last_seen DESC
                """
            )
        else:
            rows = await self._pool.fetch(
                """
                SELECT station_name, first_seen, last_seen, attempts, status, notes
                  FROM station_request
                 WHERE status = $1
              ORDER BY last_seen DESC
                """,
                status,
            )
        return [dict(r) for r in rows]

    async def get(self, station_name: str) -> dict[str, Any] | None:
        row = await self._pool.fetchrow(
            """
            SELECT station_name, first_seen, last_seen, attempts, status, notes
              FROM station_request
             WHERE station_name = $1
            """,
            station_name,
        )
        return dict(row) if row else None

    async def reject(
        self, station_name: str, *, notes: str | None = None
    ) -> bool:
        result = await self._pool.execute(
            """
            UPDATE station_request
               SET status = 'rejected',
                   notes  = COALESCE($2, notes)
             WHERE station_name = $1
            """,
            station_name, notes,
        )
        return result.endswith(" 1")

    async def restore(self, station_name: str) -> bool:
        result = await self._pool.execute(
            """
            UPDATE station_request
               SET status = 'pending'
             WHERE station_name = $1
               AND status     = 'rejected'
            """,
            station_name,
        )
        return result.endswith(" 1")

    async def approve(
        self,
        station_name: str,
        *,
        location_info: str | None,
        amr_id: str | None,
        capture_cycle: int | None,
        description: str | None,
        notes: str | None,
    ) -> dict[str, Any]:
        """Atomic: create new station row (DB generates the UUID) +
        flip the request to approved.

        Raises asyncpg.UniqueViolationError if the station_name is
        already taken (e.g. another admin approved concurrently) —
        callers should translate to HTTP 409.
        """
        async with self._pool.acquire() as conn:
            async with conn.transaction():
                station_row = await conn.fetchrow(
                    """
                    INSERT INTO station
                        (station_name, location_info, amr_id,
                         capture_cycle, description, status)
                    VALUES ($1, $2, $3, $4, $5, 'collecting')
                 RETURNING station_id, station_name, location_info, amr_id,
                           capture_cycle, description, status,
                           created_at, updated_at
                    """,
                    station_name, location_info, amr_id,
                    capture_cycle, description,
                )
                await conn.execute(
                    """
                    UPDATE station_request
                       SET status = 'approved',
                           notes  = COALESCE($2, notes)
                     WHERE station_name = $1
                    """,
                    station_name, notes,
                )
        assert station_row is not None
        return dict(station_row)

    async def status_counts(self) -> dict[str, int]:
        row = await self._pool.fetchrow(
            """
            SELECT
                COUNT(*) FILTER (WHERE status = 'pending')      AS pending,
                COUNT(*) FILTER (WHERE status = 'rejected')     AS rejected,
                COUNT(*) FILTER (WHERE status = 'approved')     AS approved,
                COALESCE(SUM(attempts), 0)                      AS total_attempts
              FROM station_request
            """
        )
        return {k: int(v) for k, v in dict(row).items()}
